---
abstract: 'Lets you build groups of accessors'
author:
  - 'Matt S. Trout <mst@shadowcatsystems.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Exception: 0.31
  Test::More: 0.94
configure_requires:
  ExtUtils::CBuilder: 0.27
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Accessor-Grouped
no_index:
  directory:
    - inc
    - t
recommends:
  Class::XSAccessor: 1.15
  Sub::Name: 0.05
requires:
  Carp: 0
  Module::Runtime: 0.012
  Scalar::Util: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://git.shadowcat.co.uk/p5sagit/Class-Accessor-Grouped.git
version: 0.10009
