---
abstract: 'Lets you build groups of accessors'
author:
  - 'Matt S. Trout <mst@shadowcatsystems.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.62
  Test::Exception: 0.31
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Accessor-Grouped
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Class::Inspector: 0
  Scalar::Util: 0
  perl: 5.6.2
resources:
  license: http://dev.perl.org/licenses/
  repository: git://git.shadowcat.co.uk/p5sagit/Class-Accessor-Grouped.git
version: 0.10006
