---
name: Class-Accessor-Grouped
version: 0.02
author:
  - 'Matt S. Trout <mst@shadowcatsystems.co.uk>'
  - 'Christopher H. Laco <claco@chrislaco.com>'
abstract: Lets you build groups of accessors
license: perl
requires:
  Carp: 0
  Class::ISA: 0
  Scalar::Util: 0
provides:
  Class::Accessor::Grouped:
    file: lib/Class/Accessor/Grouped.pm
    version: 0.02
generated_by: Module::Build version 0.26
