--- 
abstract: Lets you build groups of accessors
author: Matt S. Trout <mst@shadowcatsystems.co.uk>
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Class-Accessor-Grouped
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  Class::ISA: 0
  Scalar::Util: 0
  perl: 5.6.1
tests: t/*.t t/*/*.t
version: 0.04000
