---
abstract: 'Lets you build groups of accessors'
author:
  - 'Matt S. Trout <mst@shadowcatsystems.co.uk>'
configure_requires:
  ExtUtils::MakeMaker: 6.48
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Accessor-Grouped
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Class::Inspector: 0
  MRO::Compat: 0
  Scalar::Util: 0
  perl: 5.6.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.08002
